from enum import Enum

class Datos(Enum):
    CARLOS = "Carlos", 'M'
    LUCIA = "Lucia", 'F'
    MIGUEL = "Miguel", 'M'
    ELENA = "Elena", 'F'
    JAVIER = "Javier", 'M'
    SARA = "Sara", 'F'
    PABLO = "Pablo", 'M'
    CLARA = "Clara", 'F'
    DANIEL = "Daniel", 'M'
    MARTA = "Marta", 'F'
    LAURA = "Laura", 'F'
    DIEGO = "Diego", 'M'
    MARIA = "María", 'F'
    JUAN = "Juan", 'M'
    FRANCISCA = "Francisca", 'F'
    RAUL = "Raúl", 'M'
    CARMEN = "Carmen", 'F'
    LUIS = "Luis", 'M'
    ANA = "Ana", 'F'
    TOMAS = "Tomás", 'M'
    BEATRIZ = "Beatriz", 'F'
    ANDRES = "Andrés", 'M'
    ISABEL = "Isabel", 'F'
    ALBERTO = "Alberto", 'M'
    IGNACIA = "Ignacia",'F'
    FERNANDO = "Fernando", 'M'
    MARIANA = "Mariana", 'F'