from enum import Enum

class Datos(Enum):
    CARLOS = "Carlos"
    LUCIA = "Lucia"
    MIGUEL = "Miguel"
    ELENA = "Elena"
    JAVIER = "Javier"
    SARA = "Sara"
    PABLO = "Pablo"
    CLARA = "Clara"
    DANIEL = "Daniel"
    MARTA = "Marta"
    LAURA = "Laura"
    DIEGO = "Diego"
    MARIA = "María"
    JUAN = "Juan"
    FRANCISCA = "Francisca"
    RAUL = "Raúl"
    CARMEN = "Carmen"
    LUIS = "Luis"
    ANA = "Ana"
    TOMAS = "Tomás"
    BEATRIZ = "Beatriz"
    ANDRES = "Andrés"
    ISABEL = "Isabel"
    ALBERTO = "Alberto"
    IGNACIA = "Ignacia"
    FERNANDO = "Fernando"
    MARIANA = "Mariana"